name: Fetch Android 9 Source

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  fetch-aosp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git curl python-is-python3
          sudo apt-get install git-core gnupg flex bison build-essential zip curl zlib1g-dev libc6-dev-i386 x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig

      - name: Install repo Tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+rx ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Initialize AOSP repo (android-9.0.0_r1)
        run: |
          mkdir -p aosp/aosp-9
          cd aosp/aosp-9
          repo init -u https://github.com/enessmr/manifest -b android-9.0.0_r1 --depth=1 --partial-clone

      - name: Sync AOSP (Shallow, Clean, No Tags)
        run: |
          cd aosp/aosp-9
          repo sync -c --no-tags --no-clone-bundle -j$(nproc)
